### ISSUE TITLE
Sparkdash not able to collect information from nodes

### ISSUE THREAD

**Issue by rogargon** [brainchillz/sparkdash#1]
Running Sparkdash from the current main commit. Everything is working fine with sparkrun 0.3.4 but the dashboard just report information about vLLM, not about the nodes:

<img width="1177" height="696" alt="Image" src="https://github.com/user-attachments/assets/a1c89213-f591-4c4d-bd64-0eef8cabd669" />

When I start sparkdash, the output shows an error about the monitor_stream:

```
$ ./run.sh 
INFO:     Started server process [4172224]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on https://0.0.0.0:7862 (Press CTRL+C to quit)
[sparkdash] monitor_stream: AttributeError: 'list' object has no attribute 'items'
[sparkdash] monitor_stream: AttributeError: 'list' object has no attribute 'items'
[sparkdash] monitor_stream: AttributeError: 'list' object has no attribute 'items'
[sparkdash] monitor_stream: AttributeError: 'list' object has no attribute 'items'
[sparkdash] monitor_stream: AttributeError: 'list' object has no attribute 'items'
[sparkdash] monitor_stream: AttributeError: 'list' object has no attribute 'items'
[sparkdash] monitor_stream: AttributeError: 'list' object has no attribute 'items'
```

And what is retrived through the websocket in the web dashboard:

`{"ts":1786700359.564388,"cluster_healthy":false,"node_count":2,"ray":{"reachable":false},"vllm":{"reachable":true,"healthy":true,"model":"deepseek-ai/DeepSeek-V4-Flash-0731","max_model_len":1048576,"metrics":{"vllm:num_requests_running":0.0,"vllm:num_requests_waiting":0.0,"vllm:kv_cache_usage_perc":0.008513225904530297,"vllm:prefix_cache_queries_total":6555.0,"vllm:prefix_cache_hits_total":0.0,"vllm:prompt_tokens_total":6555.0,"vllm:generation_tokens_total":546.0,"vllm:request_success_total":4.0,"prefix_cache_hit_rate":0.0}},"recipe":{"running":false,"raw":"Job: @brainchillz/deepseek-v4-flash-0731-dspark  (tp=2)  [87d86de3a16ecbe2_d14309ba4e35]  (2 container(s))\n  node_0     192.168.0.67                             Up 53 minutes             vllm-dspark-runtime:dspark-nvfp4-stage-c-procps\n  node_1     192.168.0.45                             Up 53 minutes             vllm-dspark-runtime:dspark-nvfp4-stage-c-procps\n  logs: sparkrun logs 87d86de3a16ecbe2_d14309ba4e35\n  stop: sparkrun stop 87d86de3a16ecbe2_d14309ba4e35\n\nTotal: 2 container(s) across 2 host(s)"},"nodes":[{"name":"head","ip":"192.168.0.67","role":"head","hostname":null,"online":false,"cpu_pct":null,"cpu_load_1m":null,"cpu_temp_c":null,"cpu_freq_mhz":null,"mem_used_mb":null,"mem_total_mb":null,"mem_used_pct":null,"swap_used_mb":null,"swap_total_mb":null,"gpu_name":null,"gpu_util_pct":null,"gpu_temp_c":null,"gpu_power_w":null,"gpu_clock_mhz":null,"uptime_sec":null,"vram_used_mb":99093.0,"disk_used":981440643072,"disk_total":4031871553536},{"name":"worker","ip":"192.168.0.45","role":"worker","hostname":null,"online":false,"cpu_pct":null,"cpu_load_1m":null,"cpu_temp_c":null,"cpu_freq_mhz":null,"mem_used_mb":null,"mem_total_mb":null,"mem_used_pct":null,"swap_used_mb":null,"swap_total_mb":null,"gpu_name":null,"gpu_util_pct":null,"gpu_temp_c":null,"gpu_power_w":null,"gpu_clock_mhz":null,"uptime_sec":null,"vram_used_mb":99093.0,"disk_used":922879528960,"disk_total":4031871553536}]}	1786700357.7795455`

It was working previously with other recipes, not sure if the issue has been due to upgrading sparkrun...

**Comment by rogargon** [comment]
Tried to solve this issue with sparkrun 3.x through #2
